// =====================================================================
// HOME — the personalised daily hub.
// The two preference switches change EVERY meal instantly. While a
// subscription is active they lock (protecting the generated schedule).
// Today's delivery status now comes from the LIVE order, not a demo.
// =====================================================================

import { useMemo } from 'react'
import { Link, useNavigate } from 'react-router-dom'
import { useApp } from '../context/AppContext'
import { getDayMenu } from '../services/menuService'
import { todayString } from '../utils/date'
import { getEffectiveStatus, daysRemaining } from '../services/subscriptionService'
import { MEAL_ICONS, MEAL_LABELS } from '../data/foodItems'
import MealCard from '../components/MealCard'
import PreferenceSelector from '../components/PreferenceSelector'
import { HorizontalTracker, DELIVERY_STEPS } from '../components/StatusTracker'
import TabBar from '../components/TabBar'
import { CUISINE_LABELS, FOOD_TYPE_LABELS } from '../utils/format'
import { formatDateLong } from '../utils/date'

function greeting() {
  const h = new Date().getHours()
  if (h < 12) return 'Good morning'
  if (h < 17) return 'Good afternoon'
  return 'Good evening'
}

export default function Home() {
  const navigate = useNavigate()
  const { state, setPreferences } = useApp()
  const { profile, preferences, subscription, addresses, orders, unavailableFoodIds } = state

  const menu = useMemo(() => getDayMenu(preferences, todayString(), unavailableFoodIds), [preferences, unavailableFoodIds])

  const status = getEffectiveStatus(subscription)
  const isActive = status === 'ACTIVE'
  const remaining = subscription ? daysRemaining(subscription) : 0
  const defaultAddress = addresses.find((a) => a.isDefault) || addresses[0]

  // Today's LIVE order (auto-generated by the automation engine)
  const todaysOrder = orders.find((o) => o.date === todayString())
  const orderStep = todaysOrder ? DELIVERY_STEPS.indexOf(todaysOrder.status) : -1

  return (
    <>
      <header className="top-header">
        <div style={{ flex: 1 }}>
          <h1 className="h2">
            {greeting()}, {profile.name || 'Guest'} 👋
          </h1>
          <p className="tiny" style={{ marginTop: 2 }}>{formatDateLong(todayString())}</p>
        </div>
        <button className="icon-btn" onClick={() => navigate('/notifications')} aria-label="Notifications">
          🔔
          {state.notifications.some((n) => !n.read) && <span className="dot" />}
        </button>
        <button className="icon-btn" onClick={() => navigate('/profile')} aria-label="Profile">👤</button>
      </header>

      <div className="page stagger" style={{ paddingTop: 8 }}>
        {/* ---- Preference switches ---- */}
        <PreferenceSelector
          preferences={preferences}
          onChange={setPreferences}
          disabled={isActive}
        />

        {/* ---- Subscription status ---- */}
        {subscription && status !== 'EXPIRED' ? (
          <Link to="/subscription" style={{ textDecoration: 'none', display: 'block', marginTop: 14 }}>
            <div className="card card-hero lift">
              <div className="meal-row" style={{ marginTop: 0 }}>
                <h3 className="h2" style={{ color: '#fff' }}>📦 {subscription.planName}</h3>
                <span className="badge" style={{ background: 'rgba(255,255,255,0.22)', color: '#fff' }}>
                  {status === 'PAUSED' ? '⏸ PAUSED' : remaining <= 5 ? `⏳ ${remaining} days left` : '● ACTIVE'}
                </span>
              </div>
              <p style={{ margin: '8px 0 0', fontSize: 13, opacity: 0.95 }}>
                {FOOD_TYPE_LABELS[preferences.foodType]} • {CUISINE_LABELS[preferences.cuisine]} • {remaining} days remaining — tap to pause or skip
              </p>
            </div>
          </Link>
        ) : (
          <Link to="/plans" style={{ textDecoration: 'none', display: 'block', marginTop: 14 }}>
            <div className="card card-hero lift">
              <h3 className="h2" style={{ color: '#fff' }}>
                {status === 'EXPIRED' ? '⌛ Plan ended — renew now' : '🚀 Subscribe to a Healthy Plan'}
              </h3>
              <p style={{ margin: '6px 0 0', fontSize: 13.5, opacity: 0.95 }}>
                {status === 'EXPIRED'
                  ? 'Your previous meals are saved in history. Renew to restart daily breakfast, lunch & dinner.'
                  : 'Breakfast, lunch & dinner at your door every day — from ₹111 per meal.'}
              </p>
            </div>
          </Link>
        )}

        {/* ---- LIVE delivery status ---- */}
        {todaysOrder && (
          <Link to="/orders" style={{ textDecoration: 'none', display: 'block', marginTop: 12 }}>
            <div className="card lift">
              <div className="meal-row" style={{ marginTop: 0 }}>
                <h3 className="h2">🛵 Today&apos;s Delivery</h3>
                <span className="badge badge-amber">{todaysOrder.status}</span>
              </div>
              <HorizontalTracker currentStep={orderStep} />
              <p className="tiny" style={{ margin: '4px 0 0' }}>
                Live status — tap for details & rating
              </p>
            </div>
          </Link>
        )}

        {/* ---- Quick actions ---- */}
        <div style={{ display: 'flex', gap: 8, marginTop: 14 }}>
          <button className="link-row" style={{ marginBottom: 0, justifyContent: 'center', flex: 1 }} onClick={() => navigate('/subscription')}>
            ⏸ Pause / Skip
          </button>
          <button className="link-row" style={{ marginBottom: 0, justifyContent: 'center', flex: 1 }} onClick={() => navigate('/support')}>
            💬 Support
          </button>
        </div>

        {/* ---- Today's meals ---- */}
        <div className="section-title">
          <h2 className="h2">Today&apos;s Meals</h2>
          <Link to="/menu" style={{ fontSize: 13, color: 'var(--green)', fontWeight: 600 }}>
            Full menu →
          </Link>
        </div>
        {menu.meals.map(({ mealType, item }) => (
          <MealCard
            key={mealType}
            mealType={mealType}
            label={MEAL_LABELS[mealType]}
            icon={MEAL_ICONS[mealType]}
            item={item}
          />
        ))}

        {defaultAddress && (
          <p className="tiny" style={{ textAlign: 'center', marginTop: 18 }}>
            📍 Delivering to: {defaultAddress.label} — {defaultAddress.line.slice(0, 42)}
            {defaultAddress.line.length > 42 ? '…' : ''}
          </p>
        )}
      </div>
      <TabBar />
    </>
  )
}
